'use client';

import { cn } from '@/lib/utils';
import { 
  User, Phone, MoreVertical, Search, CheckCircle2, XCircle, 
  FileText, PanelLeftOpen, PanelLeftClose, X, UserPlus, Pause, Bot,
  Play, Download, Eye, GitBranch, Send, MessageSquare, Smartphone, Info,
  Check, CheckCheck, Tag, Trash2
} from 'lucide-react';
import React, { useEffect, useRef, useState, useCallback, useMemo } from 'react';
import { CustomerDetailsSidebar } from './CustomerDetailsSidebar';
import { MessageInput } from './message-input';
import { motion, AnimatePresence } from 'framer-motion';
import { createPortal } from 'react-dom';

interface Message {
  id: string;
  body: string;
  fromMe: boolean;
  timestamp: string;
  type?: string;
  mediaUrl?: string;
}

interface ChatWindowProps {
  conversation: any;
  messages: Message[];
  onSendMessage?: (text: string, type?: 'chat' | 'internal') => void;
  onSendMedia?: (file: File, caption?: string) => void;
  onStatusUpdate: () => void;
  onDeleted: () => void;
  onToggleSidebar: () => void;
  isSidebarCollapsed: boolean;
  onLoadMore?: () => void;
  hasMore?: boolean;
  autoGenerateReport?: boolean;
}

export function ChatWindow({ 
  conversation, 
  messages, 
  onSendMessage,
  onSendMedia,
  onStatusUpdate, 
  onDeleted,
  onToggleSidebar,
  isSidebarCollapsed,
  onLoadMore,
  hasMore,
  autoGenerateReport = false
}: ChatWindowProps) {
  const [updating, setUpdating] = useState(false);
  const [isSearching, setIsSearching] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [menuOpen, setMenuOpen] = useState(false);
  const [localIsBotActive, setLocalIsBotActive] = useState(conversation?.isBotActive || false);
  
  // Sincroniza estado local quando a prop muda
  useEffect(() => {
    setLocalIsBotActive(conversation?.isBotActive || false);
  }, [conversation?.isBotActive]);
  
  // Modals state
  const [activeModal, setActiveModal] = useState<'transfer' | 'edit' | 'note' | 'pdf-preview' | 'report-config' | null>(null);
  const [users, setUsers] = useState<any[]>([]);
  const [departments, setDepartments] = useState<any[]>([]);
  const [selectedUser, setSelectedUser] = useState('');
  const [selectedDepartment, setSelectedDepartment] = useState('');
  const [contactName, setContactName] = useState(conversation.contact.name || '');
  const [contactEmail, setContactEmail] = useState(conversation.contact.email || '');
  const [contactNotes, setContactNotes] = useState(conversation.contact.notes || '');
  const [contactObservations, setContactObservations] = useState(conversation.contact.observations || '');
  const [showDetails, setShowDetails] = useState(false);
  
  // Report Config
  const [reportType, setReportType] = useState<'all' | 'ticket'>('all');
  const [selectedTicketId, setSelectedTicketId] = useState(conversation.id);
  const [availableTickets, setAvailableTickets] = useState<any[]>([]);
  const [allContactMessages, setAllContactMessages] = useState<any[]>([]);

  const scrollRef = useRef<HTMLDivElement>(null);
  const isInitialLoad = useRef(true);
  const prevScrollHeight = useRef(0);
  const isFetchingMore = useRef(false);

  // Atualiza estados quando a conversa muda
  useEffect(() => {
    isInitialLoad.current = true;
    setContactName(conversation.contact.name || '');
    setContactEmail(conversation.contact.email || '');
    setContactNotes(conversation.contact.notes || '');
    setContactObservations(conversation.contact.observations || '');
  }, [conversation.id]);

  const hasAutoGenerated = useRef<string | null>(null);

  // Autogerador de Relatório (vindo do Planner)
  useEffect(() => {
    if (autoGenerateReport && conversation.id && hasAutoGenerated.current !== conversation.id) {
      hasAutoGenerated.current = conversation.id;
      
      // Carrega tickets se ainda não tiver, mas já define o ticket alvo
      if (availableTickets.length === 0) {
        fetch(`/api/conversations?contactId=${conversation.contact.id}`)
          .then(res => res.json())
          .then(data => setAvailableTickets(data));
      }

      setReportType('ticket');
      setSelectedTicketId(conversation.id);
      
      // Chama a geração direta sem passar pela janela de configuração
      setTimeout(() => {
        handleGeneratePreview();
        
        // Limpa a URL para evitar repetições (usando window.history para ser silencioso)
        const url = new URL(window.location.href);
        url.searchParams.delete('generateReport');
        url.searchParams.delete('id');
        window.history.replaceState({}, '', url.toString());
      }, 1000);
    }
  }, [autoGenerateReport, conversation.id]);

  useEffect(() => {
    if (activeModal === 'transfer') {
      if (users.length === 0) {
        fetch('/api/users').then(res => res.json()).then(data => {
          if(Array.isArray(data)) setUsers(data);
        });
      }
      if (departments.length === 0) {
        fetch('/api/departments').then(res => res.json()).then(data => {
          if(Array.isArray(data)) setDepartments(data);
        });
      }
    }
    if (activeModal === 'edit') {
      setContactName(conversation?.contact?.name || conversation?.contact?.number || '');
    }
  }, [activeModal, conversation, users.length, departments.length]);

  const getMessageTime = (m: any) => {
    const date = m.createdAt || m.timestamp;
    return date ? new Date(date).getTime() : 0;
  };

  const displayedMessages = useMemo(() => {
    const raw = searchTerm 
      ? messages.filter(m => m.body?.toLowerCase().includes(searchTerm.toLowerCase()))
      : messages;
    
    const unique = raw.filter((m, index, self) => 
      index === self.findIndex((t) => String(t.id) === String(m.id))
    );
    
    return unique.sort((a, b) => getMessageTime(b) - getMessageTime(a));
  }, [messages, searchTerm]);

  const exportMessages = useMemo(() => {
    return [...allContactMessages].sort((a, b) => getMessageTime(a) - getMessageTime(b));
  }, [allContactMessages]);

  const handleScroll = useCallback((e: React.UIEvent<HTMLDivElement>) => {
    const { scrollTop, scrollHeight, clientHeight } = e.currentTarget;
    // No flex-col-reverse, o topo (mensagens antigas) é quando o scrollTop atinge o limite superior
    // Math.abs para lidar com variações de browser em col-reverse
    const isAtTop = Math.abs(scrollTop) + clientHeight >= scrollHeight - 50;

    if (isAtTop && hasMore && !isFetchingMore.current && !searchTerm) {
      isFetchingMore.current = true;
      prevScrollHeight.current = e.currentTarget.scrollHeight;
      onLoadMore?.();
    }
  }, [hasMore, onLoadMore, searchTerm]);

  useEffect(() => {
    if (scrollRef.current) {
      if (isInitialLoad.current) {
        scrollRef.current.scrollTop = 0;
        isInitialLoad.current = false;
      } else if (!isFetchingMore.current) {
        // Se não for carregamento de histórico, rola para o fundo (0 no reverse)
        scrollRef.current.scrollTo({ top: 0, behavior: 'smooth' });
      }
      isFetchingMore.current = false;
    }
  }, [messages]);

  const handleAccept = async () => {
    setUpdating(true);
    try {
      const res = await fetch(`/api/conversations/${conversation.id}/accept`, { method: 'POST' });
      if (res.ok) onStatusUpdate();
    } catch (err) {
      console.error(err);
    } finally {
      setUpdating(false);
    }
  };

  const handleClose = async () => {
    if (!window.confirm('Deseja encerrar este atendimento?')) return;
    setUpdating(true);
    try {
      const res = await fetch(`/api/conversations/${conversation.id}/close`, { method: 'POST' });
      if (res.ok) {
        onStatusUpdate();
      } else {
        const errorData = await res.json();
        alert(`Erro ao encerrar atendimento: ${errorData.error || 'Erro desconhecido'}`);
      }
    } catch (err) {
      console.error('Erro ao fechar conversa:', err);
      alert('Erro de conexão ao tentar encerrar o atendimento.');
    } finally {
      setUpdating(false);
    }
  };

  const handleReopen = async () => {
    if (!window.confirm('Deseja reabrir este atendimento?')) return;
    setUpdating(true);
    try {
      const res = await fetch(`/api/conversations/${conversation.id}/reopen`, { method: 'POST' });
      if (res.ok) {
        onStatusUpdate();
      }
    } catch (err) {
      console.error(err);
    } finally {
      setUpdating(false);
      setMenuOpen(false);
    }
  };

  const handleDeleteConversation = async () => {
    if (!confirm('ATENÇÃO: Deseja realmente excluir permanentemente esta conversa e todas as suas mensagens?')) return;
    setUpdating(true);
    try {
      const res = await fetch(`/api/conversations/${conversation.id}`, { method: 'DELETE' });
      if (res.ok) {
        if (onDeleted) onDeleted();
        onStatusUpdate();
      }
    } catch (err) {
      console.error(err);
    } finally {
      setUpdating(false);
    }
  };

  const handleDeleteContact = async () => {
    if (!confirm('ATENÇÃO: Deseja realmente excluir este contato e TODAS as suas conversas?')) return;
    setUpdating(true);
    try {
      const res = await fetch(`/api/contacts/${conversation.contact.id}`, { method: 'DELETE' });
      if (res.ok) {
        setActiveModal(null);
        if (onDeleted) onDeleted();
        onStatusUpdate();
      }
    } catch (err) {
      console.error(err);
    } finally {
      setUpdating(false);
    }
  };

  const handleToggleBot = async () => {
    setUpdating(true);
    const newState = !localIsBotActive;
    setLocalIsBotActive(newState); // Mudança instantânea na UI
    try {
      const res = await fetch(`/api/conversations/${conversation.id}/bot`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ active: newState })
      });
      if (res.ok) {
        onStatusUpdate();
      } else {
        // Reverte se der erro
        setLocalIsBotActive(!newState);
      }
    } catch (err) {
      console.error(err);
      setLocalIsBotActive(!newState);
    } finally {
      setUpdating(false);
    }
  };

  const handleTransfer = async () => {
    if (!selectedUser && !selectedDepartment) return;
    setUpdating(true);
    try {
      const res = await fetch(`/api/conversations/${conversation.id}/transfer`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ userId: selectedUser || null, departmentId: selectedDepartment || null })
      });
      if (res.ok) {
        setActiveModal(null);
        setSelectedUser('');
        setSelectedDepartment('');
        onStatusUpdate();
      }
    } catch (err) {
      console.error(err);
    } finally {
      setUpdating(false);
    }
  };

  const handleExportPDF = async () => {
    if (!messages || messages.length === 0) return;
    
    setUpdating(true);
    setMenuOpen(false);
    
    try {
      const jsPDF = await import('jspdf').then(m => m.default);
      let imgData = pdfPreviewUrl;

      const element = document.getElementById('pdf-export-container');
      if (!element) return;

      if (!imgData) {
        const { toPng } = await import('html-to-image');
        
        document.body.classList.add('is-exporting-pdf');
        await new Promise(resolve => setTimeout(resolve, 500));
        
        imgData = await toPng(element, {
          backgroundColor: '#0b141a',
          quality: 1,
          pixelRatio: 2,
          width: 850,
          style: { height: 'auto', maxHeight: 'none', overflow: 'visible', width: '850px', display: 'flex' }
        });
        document.body.classList.remove('is-exporting-pdf');
      }

      if (!imgData) return;

      const pdfTemp = new jsPDF();
      const imgProps = pdfTemp.getImageProperties(imgData);
      
      // Criamos o PDF com o tamanho EXATO da imagem para evitar espaços em branco
      const pdf = new jsPDF({
        orientation: imgProps.width > imgProps.height ? 'landscape' : 'portrait',
        unit: 'px',
        format: [imgProps.width, imgProps.height]
      });

      pdf.addImage(imgData, 'PNG', 0, 0, imgProps.width, imgProps.height);
      pdf.save(`conversa-${conversation.contact.name || conversation.contact.number}-${new Date().toLocaleDateString()}.pdf`);
    } catch (err) {
      console.error('Erro ao exportar PDF:', err);
      alert('Erro ao gerar PDF. O sistema de captura moderno encontrou uma restrição visual.');
    } finally {
      setUpdating(false);
    }
  };

  const [pdfPreviewUrl, setPdfPreviewUrl] = useState<string | null>(null);
  const [isGeneratingPreview, setIsGeneratingPreview] = useState(false);

  const handleOpenReportConfig = async () => {
    setUpdating(true);
    setMenuOpen(false);
    try {
      const res = await fetch(`/api/conversations?contactId=${conversation.contact.id}`);
      if (res.ok) {
        const data = await res.json();
        setAvailableTickets(data);
        setActiveModal('report-config');
      }
    } catch (err) {
      console.error('Erro ao buscar tickets:', err);
      alert('Erro ao carregar lista de tickets.');
    } finally {
      setUpdating(false);
    }
  };

  const handleGeneratePreview = async () => {
    if (!conversation.contact.id) return;
    
    setIsGeneratingPreview(true);
    setUpdating(true);
    
    try {
      const targetId = reportType === 'ticket' ? selectedTicketId : conversation.id;
      const res = await fetch(`/api/conversations/${targetId}/messages?scope=${reportType}&limit=5000`);
      
      if (!res.ok) throw new Error('Falha ao buscar mensagens');
      
      const data = await res.json();
      const messagesArray = Array.isArray(data) ? data : (data.messages || []);
      
      setAllContactMessages(messagesArray);
      
      // Delay para garantir que o state de mensagens foi processado e o DOM atualizado
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      const { toPng } = await import('html-to-image');
      
      // Tenta localizar o elemento com retentativas (resiliência para montagem lenta)
      let element = document.getElementById('pdf-export-container');
      let attempts = 0;
      while (!element && attempts < 25) { // Tenta por até 5 segundos (25 * 200ms)
        await new Promise(resolve => setTimeout(resolve, 200));
        element = document.getElementById('pdf-export-container');
        attempts++;
      }
      
      if (!element) throw new Error("Erro ao localizar container de impressão após várias tentativas");

      const imgData = await toPng(element, {
        cacheBust: true,
        backgroundColor: '#0b141a',
        pixelRatio: 2,
        quality: 1,
        style: {
          opacity: '1',
          visibility: 'visible',
          fontFamily: 'sans-serif'
        }
      });

      setPdfPreviewUrl(imgData);
      setActiveModal('pdf-preview');
    } catch (err: any) {
      console.error('Erro:', err);
      alert('Erro ao gerar relatório. Tente novamente.');
    } finally {
      setIsGeneratingPreview(false);
      setUpdating(false);
    }
  };

  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  // Limpeza de Blobs por segurança e memória
  useEffect(() => {
    return () => {
      if (pdfPreviewUrl && pdfPreviewUrl.startsWith('blob:')) {
        URL.revokeObjectURL(pdfPreviewUrl);
      }
    };
  }, [pdfPreviewUrl]);

  const handleCloseModal = () => {
    if (activeModal === 'pdf-preview' && pdfPreviewUrl && pdfPreviewUrl.startsWith('blob:')) {
      URL.revokeObjectURL(pdfPreviewUrl);
      setPdfPreviewUrl(null);
    }
    setActiveModal(null);
  };

  const getDayLabel = (dateString: string) => {
    const date = new Date(dateString);
    const today = new Date();
    const yesterday = new Date(today);
    yesterday.setDate(yesterday.getDate() - 1);

    if (date.toDateString() === today.toDateString()) return 'Hoje';
    if (date.toDateString() === yesterday.toDateString()) return 'Ontem';
    
    return date.toLocaleDateString('pt-BR', { 
      day: '2-digit', 
      month: 'long', 
      year: date.getFullYear() !== today.getFullYear() ? 'numeric' : undefined 
    });
  };

  const handleUpdateContact = async (data: { name?: string, notes?: string, observations?: string, email?: string }) => {
    setUpdating(true);
    try {
      const res = await fetch(`/api/contacts/${conversation.contact.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data)
      });
      
      if (!res.ok) {
        throw new Error('Falha ao atualizar contato');
      }

      onStatusUpdate();
      setActiveModal(null);
    } catch (err) {
      console.error('Erro ao atualizar contato:', err);
    } finally {
      setUpdating(false);
    }
  };

  if (!conversation) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center bg-[#0b141a] text-slate-500 p-8 text-center relative overflow-hidden">
        {/* Decorative background pulse */}
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-emerald-500/5 rounded-full blur-[100px] animate-pulse" />
        
        <div className="relative z-10">
          <div className="w-24 h-24 rounded-[2.5rem] bg-white/5 flex items-center justify-center mb-8 mx-auto border border-white/10 shadow-2xl group transition-all duration-700 hover:scale-110">
            <MessageSquare size={48} className="text-emerald-500/50 group-hover:text-emerald-500 transition-colors" />
          </div>
          <h2 className="text-3xl font-black text-white mb-4 tracking-tighter">Bem-vindo ao Chatinho</h2>
          <p className="max-w-md text-slate-400 text-sm leading-relaxed mb-10">
            Selecione uma conversa na lista lateral para iniciar o atendimento ou verifique a fila de espera.
          </p>
          
          <div className="grid grid-cols-2 gap-4 max-w-sm mx-auto">
            <button className="px-6 py-3 bg-white/5 border border-white/10 rounded-2xl text-[11px] font-black uppercase tracking-widest text-slate-300 hover:bg-white/10 transition-all">
              Ver Minhas Tarefas
            </button>
            <button className="px-6 py-3 bg-white/5 border border-white/10 rounded-2xl text-[11px] font-black uppercase tracking-widest text-slate-300 hover:bg-white/10 transition-all">
              Fila de Espera
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex-1 flex flex-col h-full relative overflow-hidden bg-slate-950/20">
      {/* Background Pattern */}
      <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-[0.03] pointer-events-none" />
      
      {/* Header */}
      <div className="px-6 py-4 bg-white/[0.03] backdrop-blur-xl flex items-center justify-between z-30 relative border-b border-white/5 shadow-xl">
        <div className="flex items-center gap-4">
          <button
            onClick={onToggleSidebar}
            className="p-2.5 text-slate-500 hover:text-white hover:bg-white/5 rounded-xl transition-all"
            title={isSidebarCollapsed ? "Expandir Menu" : "Recolher Menu"}
          >
            {isSidebarCollapsed ? <PanelLeftOpen size={20} /> : <PanelLeftClose size={20} />}
          </button>

          <div className="flex items-center gap-4">
            <div className="relative group">
              <div 
                className={cn(
                  "w-12 h-12 rounded-2xl border border-white/10 flex items-center justify-center overflow-hidden shadow-2xl cursor-pointer group transition-all duration-500 hover:scale-105",
                  conversation.contact.profilePic ? "bg-white/5" : "bg-slate-800"
                )} 
                onClick={() => setActiveModal('edit')}
              >
                {conversation.contact.profilePic ? (
                  <img 
                    src={conversation.contact.profilePic} 
                    alt={conversation.contact.name || ''} 
                    className="w-full h-full object-cover"
                  />
                ) : (
                  <span className="text-xl font-black text-emerald-500 tracking-tighter">
                    {(conversation.contact.name || 'C').charAt(0).toUpperCase()}
                  </span>
                )}
              </div>
              <div className={cn(
                "absolute -bottom-1 -right-1 w-4 h-4 rounded-full border-2 border-[#020617] shadow-lg",
                conversation.status === 'QUEUED' ? "bg-amber-500 animate-pulse" : "bg-emerald-500"
              )} />
            </div>
            
            <div className="flex flex-col">
              <div className="flex items-center gap-2 mb-1">
                <h2 className="text-xl font-black text-white tracking-tight leading-none">
                  {conversation.contact.name || conversation.contact.number}
                </h2>
                <div className={cn(
                  "flex items-center gap-1.5 px-2 py-0.5 rounded-md border text-[9px] font-black uppercase tracking-widest",
                  conversation.platform === 'TELEGRAM' 
                    ? "bg-blue-500/10 border-blue-500/20 text-blue-400" 
                    : "bg-emerald-500/10 border-emerald-500/20 text-emerald-400"
                )}>
                  {conversation.platform === 'TELEGRAM' ? <Send size={10} /> : <MessageSquare size={10} />}
                  {conversation.platform || 'WHATSAPP'}
                </div>
              </div>
              
              <div className="flex items-center gap-3">
                <div className={cn(
                  "flex items-center gap-1.5 px-2 py-0.5 rounded-md text-[9px] font-black uppercase tracking-widest border",
                  conversation.status === 'QUEUED' ? "bg-amber-500/10 border-amber-500/20 text-amber-500" :
                  conversation.status === 'ACTIVE' ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-500" :
                  "bg-slate-500/10 border-white/5 text-slate-500"
                )}>
                  {conversation.status === 'QUEUED' ? 'EM FILA' :
                   conversation.status === 'ACTIVE' ? 'EM ATENDIMENTO' : 'FECHADO'}
                </div>
                <span className="w-1 h-1 rounded-full bg-slate-700" />
                <span className="text-[10px] font-black text-slate-500 uppercase tracking-widest">
                  Ticket #{conversation.protocol || '---'}
                </span>
                <span className="w-1 h-1 rounded-full bg-slate-700" />
                <span className="text-[10px] font-bold text-slate-500">
                  {conversation.contact.number}
                </span>
              </div>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {/* Busca na Conversa */}
          <div className="flex items-center gap-2">
            <AnimatePresence>
              {isSearching && (
                <motion.div 
                  initial={{ width: 0, opacity: 0 }}
                  animate={{ width: 'auto', opacity: 1 }}
                  exit={{ width: 0, opacity: 0 }}
                  className="overflow-hidden flex items-center bg-white/5 border border-white/10 rounded-xl px-3 py-1.5"
                >
                  <Search size={14} className="text-slate-500" />
                  <input 
                    autoFocus
                    type="text"
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    placeholder="Buscar mensagens..."
                    className="bg-transparent border-none outline-none text-xs text-white placeholder-slate-600 ml-2 w-32 lg:w-48"
                  />
                  <X 
                    size={14} 
                    className="text-slate-500 hover:text-white cursor-pointer ml-2" 
                    onClick={() => { setIsSearching(false); setSearchTerm(''); }} 
                  />
                </motion.div>
              )}
            </AnimatePresence>
            
            {!isSearching && (
              <button 
                onClick={() => setIsSearching(true)}
                className="p-2.5 text-slate-400 hover:text-white hover:bg-white/5 rounded-xl transition-all"
              >
                <Search size={20} />
              </button>
            )}
          </div>

          <div className="w-px h-6 bg-white/10 mx-1" />

          {conversation.status === 'QUEUED' && (
            <motion.button
              whileHover={{ scale: 1.02 }}
              whileTap={{ scale: 0.98 }}
              onClick={handleAccept}
              disabled={updating}
              className="flex items-center gap-2 px-5 py-2 bg-emerald-500 text-slate-950 text-xs font-black rounded-xl transition-all shadow-lg shadow-emerald-500/20 disabled:opacity-50"
            >
              <UserPlus size={16} strokeWidth={2.5} />
              ACEITAR
            </motion.button>
          )}

          <div className="flex items-center bg-white/5 rounded-xl p-1 border border-white/5">
            {conversation.status !== 'CLOSED' && (
              <button
                onClick={handleToggleBot}
                disabled={updating}
                className={cn(
                  "p-2 rounded-lg transition-all relative group",
                  localIsBotActive ? "text-amber-500 bg-amber-500/10" : "text-slate-500 hover:text-blue-400 hover:bg-blue-400/10"
                )}
                title={localIsBotActive ? "Pausar Robô" : "Ativar Robô"}
              >
                {localIsBotActive ? <Pause size={18} /> : <Bot size={18} />}
              </button>
            )}

            {conversation.status === 'ACTIVE' ? (
              <button
                onClick={handleClose}
                disabled={updating}
                className="p-2 text-slate-500 hover:text-red-400 hover:bg-red-400/10 rounded-lg transition-all"
                title="Fechar Conversa"
              >
                <XCircle size={18} />
              </button>
            ) : conversation.status === 'CLOSED' ? (
              <button
                onClick={handleReopen}
                disabled={updating}
                className="p-2 text-slate-500 hover:text-emerald-400 hover:bg-emerald-400/10 rounded-lg transition-all"
                title="Reabrir Conversa"
              >
                <Play size={18} />
              </button>
            ) : null}
            
            <div className="w-px h-4 bg-white/10 mx-1" />
            
            <button 
              onClick={() => setMenuOpen(!menuOpen)}
              className={cn(
                "p-2 rounded-lg transition-all",
                menuOpen ? "text-white bg-white/10" : "text-slate-500 hover:text-white"
              )}
            >
              <MoreVertical size={18} />
            </button>
          </div>

          <button 
            onClick={() => setShowDetails(!showDetails)}
            className={cn(
              "p-2.5 rounded-xl transition-all border",
              showDetails 
                ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-400" 
                : "bg-white/5 border-white/5 text-slate-500 hover:text-white"
            )}
            title="Dados do Cliente"
          >
            <Info size={20} />
          </button>
        </div>
      </div>

      <div className="flex-1 flex overflow-hidden relative">
        {/* Main Chat Area */}
        <div className="flex-1 flex flex-col h-full relative min-w-0">
          <AnimatePresence>
            {menuOpen && (
              <>
                <div 
                  className="fixed inset-0 z-40" 
                  onClick={() => setMenuOpen(false)} 
                />
                <motion.div
                  initial={{ opacity: 0, y: 10, scale: 0.95 }}
                  animate={{ opacity: 1, y: 0, scale: 1 }}
                  exit={{ opacity: 0, y: 10, scale: 0.95 }}
                  className="absolute right-6 top-2 w-72 bg-slate-900/95 backdrop-blur-xl border border-white/10 rounded-2xl shadow-2xl z-50 py-3 overflow-hidden"
                >
                  <div className="px-4 py-2 border-b border-white/5 mb-2">
                    <span className="text-[10px] font-black uppercase tracking-widest text-slate-500">Ações Rápidas</span>
                  </div>

                  {(conversation.contact.notes || conversation.contact.observations) && (
                    <div className="px-4 py-3 bg-slate-950/40 border-y border-white/5 mb-2 space-y-3">
                      {conversation.contact.notes && (
                        <div>
                          <span className="text-[9px] font-black text-amber-500 uppercase tracking-widest block mb-1">Notas Rápidas</span>
                          <p className="text-[11px] text-slate-400 italic whitespace-pre-wrap">"{conversation.contact.notes}"</p>
                        </div>
                      )}
                      {conversation.contact.observations && (
                        <div>
                          <span className="text-[9px] font-black text-blue-400 uppercase tracking-widest block mb-1">Observações</span>
                          <p className="text-[11px] text-slate-400 italic whitespace-pre-wrap">"{conversation.contact.observations}"</p>
                        </div>
                      )}
                    </div>
                  )}
                  
                  <button
                    onClick={() => {
                      setMenuOpen(false);
                      setActiveModal('transfer');
                    }}
                    className="w-full flex items-center gap-3 px-4 py-2.5 text-slate-300 hover:text-white hover:bg-white/5 transition-all text-sm"
                  >
                    <UserPlus size={16} />
                    Transferir Atendimento
                  </button>

                  <button
                    onClick={handleOpenReportConfig}
                    disabled={updating || isGeneratingPreview}
                    className="w-full flex items-center gap-3 px-4 py-2.5 text-slate-300 hover:text-white hover:bg-white/5 transition-all text-sm disabled:opacity-50"
                  >
                    <Eye size={16} />
                    Visualizar Relatório (PDF)
                  </button>

                  <div className="h-px bg-white/5 my-2" />

                  <button
                    onClick={() => {
                      setMenuOpen(false);
                      handleDeleteConversation();
                    }}
                    className="w-full flex items-center gap-3 px-4 py-2.5 text-red-400 hover:text-red-300 hover:bg-red-500/10 transition-all text-sm"
                  >
                    <Trash2 size={16} />
                    Excluir Toda a Conversa
                  </button>
                </motion.div>
              </>
            )}
          </AnimatePresence>

          {/* Messages Area */}
      <div 
        ref={scrollRef}
        id="messages-container"
        onScroll={handleScroll}
        className="flex-1 overflow-y-auto px-6 py-8 flex flex-col-reverse z-10 custom-scrollbar bg-[#0b141a]"
      >
        <AnimatePresence initial={false}>
          {displayedMessages.map((msg: any, idx) => {
            const prevMsg: any = idx < displayedMessages.length - 1 ? displayedMessages[idx + 1] : null; // Mensagem mais antiga na UI
            
            const isNewProtocol = !prevMsg || prevMsg.conversationId !== msg.conversationId;
            const isNewDay = !prevMsg || new Date(msg.timestamp).toDateString() !== new Date(prevMsg.timestamp).toDateString();
            
            return (
              <React.Fragment key={msg.id}>
                <div className="mt-2">
                  <MessageItem 
                    msg={msg} 
                    idx={idx} 
                    conversation={conversation} 
                    totalMessages={displayedMessages.length}
                    onPlayAudio={() => {}} 
                    shouldAnimate={!isInitialLoad.current && !isFetchingMore.current}
                  />
                </div>

                {isNewProtocol && (
                  <motion.div 
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="flex flex-col items-center justify-center py-6 relative"
                  >
                    <div className="absolute inset-x-0 top-1/2 h-px bg-gradient-to-r from-transparent via-white/5 to-transparent" />
                    <div className="relative flex flex-col items-center gap-1.5">
                      <div className="px-3 py-1 bg-slate-900 border border-white/5 rounded-full shadow-lg flex items-center gap-2">
                        <div className={cn(
                          "w-1 h-1 rounded-full",
                          msg.conversation?.status === 'CLOSED' ? "bg-slate-500" : "bg-emerald-500 animate-pulse"
                        )} />
                        <span className="text-[9px] font-black text-slate-300 uppercase tracking-widest">
                          Ticket #{msg.conversation?.protocol || 'Protocolo...'}
                        </span>
                      </div>
                    </div>
                  </motion.div>
                )}

                {isNewDay && (
                  <div className="flex justify-center my-8 relative">
                    <div className="absolute inset-x-0 top-1/2 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent" />
                    <span className="relative px-4 py-1.5 bg-[#0b141a] border border-white/10 rounded-full text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] shadow-2xl">
                      {getDayLabel(msg.timestamp)}
                    </span>
                  </div>
                )}
              </React.Fragment>
            );
          })}
        </AnimatePresence>

        {hasMore && (
          <div className="flex justify-center py-4">
             <div className="w-6 h-6 border-2 border-emerald-500/30 border-t-emerald-500 rounded-full animate-spin" />
          </div>
        )}

          </div>

          {/* Message Input Area */}
          <div className="p-4 bg-white/[0.02] border-t border-white/5 backdrop-blur-md">
            <MessageInput 
              onSend={onSendMessage || (() => {})}
              onSendMedia={onSendMedia || (() => {})}
              disabled={updating || conversation.status === 'CLOSED'}
            />
          </div>
        </div>

        {/* Customer Details Sidebar Integration */}
        <AnimatePresence>
          {showDetails && (
            <div className="h-full z-40 border-l border-white/5 bg-[#0b141a]/50 backdrop-blur-xl">
              <CustomerDetailsSidebar 
                conversation={conversation} 
                onClose={() => setShowDetails(false)} 
                onEdit={() => setActiveModal('edit')}
              />
            </div>
          )}
        </AnimatePresence>

        {/* PDF Export Container (Classic Rendering) */}
        <div 
          id="pdf-export-container" 
          className="absolute top-0 left-0 flex flex-col bg-[#0b141a] p-12 w-[850px] opacity-0 pointer-events-none"
          style={{ 
            zIndex: -1,
            height: 'auto',
            display: 'flex',
            color: 'white'
          }}
        >
          {/* Header Premium do PDF */}
          <div className="flex flex-col gap-6 mb-12 p-8 bg-[#111b21] rounded-[2.5rem] border border-white/10 items-start justify-between w-full">
            <div className="flex items-center gap-6 w-full">
              <div className="w-20 h-20 rounded-3xl bg-emerald-500/20 border border-emerald-500/30 flex items-center justify-center text-emerald-500 shrink-0">
                <User size={40} />
              </div>
              <div className="flex-1">
                <div className="flex items-center gap-3">
                  <h1 className="text-4xl font-black text-white tracking-tight">{conversation.contact.name || 'Contato'}</h1>
                  <span className="px-3 py-1 bg-emerald-500/10 text-emerald-500 rounded-full text-[10px] font-black uppercase tracking-widest border border-emerald-500/20">Relatório Oficial</span>
                </div>
                <p className="text-slate-400 font-bold text-lg mt-1">{conversation.contact.number}</p>
              </div>
              <div className="text-right shrink-0">
                <p className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500 mb-2">Data de Geração</p>
                <p className="text-white font-bold text-xl">{new Date().toLocaleDateString('pt-BR', { day: '2-digit', month: 'long', year: 'numeric' })}</p>
                <p className="text-slate-500 text-xs mt-1 font-medium italic">Sistema Chatinho v2.3.7</p>
              </div>
            </div>
            <div className="h-px bg-white/10 w-full mt-4" />
          </div>

          <div className="flex flex-col gap-4 w-full">
            {exportMessages.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-40 bg-slate-900 rounded-3xl border-4 border-emerald-500/20 border-dashed">
                <MessageSquare size={64} className="text-emerald-500/30 mb-6" />
                <p className="text-white font-black uppercase tracking-widest text-lg">Aguardando dados das mensagens...</p>
              </div>
            ) : (
              exportMessages.map((msg: any, idx) => {
                const prevMsg: any = idx > 0 ? exportMessages[idx - 1] : null;
                const isNewProtocol = !prevMsg || prevMsg.conversationId !== msg.conversationId;
                const isNewDay = !prevMsg || new Date(msg.timestamp).toDateString() !== new Date(prevMsg.timestamp).toDateString();
                
                return (
                  <React.Fragment key={msg.id}>
                    {isNewDay && (
                      <div className="flex justify-center my-8 relative">
                        <div className="absolute inset-x-0 top-1/2 h-px bg-white/10" />
                        <span className="relative px-4 py-1 bg-[#0b141a] text-[10px] font-black text-slate-400 uppercase tracking-widest">
                          {getDayLabel(msg.timestamp)}
                        </span>
                      </div>
                    )}

                    {isNewProtocol && (
                      <div className="flex flex-col items-center justify-center py-6 relative">
                        <div className="absolute inset-x-0 top-1/2 h-px bg-white/5" />
                        <div className="relative px-4 py-2 bg-[#111b21] border border-white/10 rounded-full shadow-2xl">
                          <span className="text-[10px] font-black text-emerald-500 uppercase tracking-[0.2em]">
                            Início de Ticket #{msg.conversation?.protocol || selectedTicketId || '---'}
                          </span>
                        </div>
                      </div>
                    )}

                    <div className={cn(
                      "flex w-full mb-3",
                      msg.fromMe ? "justify-end" : "justify-start"
                    )}>
                      <div className={cn(
                        "max-w-[80%] rounded-[1.5rem] p-5 shadow-xl",
                        msg.fromMe ? "bg-[#00a884] text-white" : "bg-[#202c33] text-white border border-white/5"
                      )}>
                        <p className="text-[15px] leading-relaxed whitespace-pre-wrap break-words font-medium">{msg.body}</p>
                        <div className="flex justify-end mt-2 opacity-40">
                          <span className="text-[10px] font-bold tracking-tighter">
                            {new Date(msg.timestamp).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}
                          </span>
                        </div>
                      </div>
                    </div>
                  </React.Fragment>
                );
              })
            )}
          </div>

          <div className="mt-20 pt-10 border-t border-white/5 text-center">
            <p className="text-slate-600 text-[10px] font-black uppercase tracking-[0.5em]">Fim do Relatório • Gerado em {new Date().toLocaleString()}</p>
          </div>
        </div>
      </div>

      {mounted && activeModal && createPortal(
        <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4 md:p-6 animate-in fade-in duration-300">
          <div 
            className="absolute inset-0 bg-slate-950/60 backdrop-blur-md" 
            onClick={handleCloseModal} 
          />
          <div className={cn(
            "relative w-full glass-modal premium-shadow rounded-3xl overflow-hidden animate-in zoom-in-95 duration-300",
            activeModal === 'pdf-preview' ? "max-w-5xl h-[90vh]" : "max-w-md p-6"
          )}>
            {activeModal === 'report-config' && (
              <>
                <h3 className="text-lg font-semibold text-white mb-4">Configurar Relatório (PDF)</h3>
                <div className="space-y-6 mb-6">
                  <div>
                    <label className="block text-[10px] font-black text-[#8696a0] uppercase tracking-widest mb-3">Abrangência do Relatório</label>
                    <div className="grid grid-cols-2 gap-3">
                      <button 
                        onClick={() => setReportType('all')}
                        className={cn(
                          "px-4 py-3 rounded-xl border transition-all flex flex-col items-center gap-2",
                          reportType === 'all' 
                            ? "bg-emerald-500/10 border-emerald-500/30 text-emerald-400 shadow-lg shadow-emerald-500/10" 
                            : "bg-white/5 border-white/5 text-slate-500 hover:border-white/10"
                        )}
                      >
                        <MessageSquare size={18} />
                        <span className="text-[10px] font-bold">HISTÓRICO COMPLETO</span>
                      </button>
                      <button 
                        onClick={() => setReportType('ticket')}
                        className={cn(
                          "px-4 py-3 rounded-xl border transition-all flex flex-col items-center gap-2",
                          reportType === 'ticket' 
                            ? "bg-blue-500/10 border-blue-500/30 text-blue-400 shadow-lg shadow-blue-500/10" 
                            : "bg-white/5 border-white/5 text-slate-500 hover:border-white/10"
                        )}
                      >
                        <Tag size={18} />
                        <span className="text-[10px] font-bold">APENAS UM TICKET</span>
                      </button>
                    </div>
                  </div>

                  {reportType === 'ticket' && (
                    <motion.div 
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      className="space-y-2"
                    >
                      <label className="block text-[10px] font-black text-[#8696a0] uppercase tracking-widest mb-2">Selecione o Ticket</label>
                      <select 
                        value={selectedTicketId} 
                        onChange={(e) => setSelectedTicketId(e.target.value)}
                        className="w-full bg-[#2a3942] border border-white/10 rounded-lg p-3 text-white outline-none focus:border-[#00a884] transition-all"
                      >
                        {availableTickets.map(ticket => (
                          <option key={ticket.id} value={ticket.id}>
                            Ticket #{ticket.protocol || '---'} ({new Date(ticket.createdAt).toLocaleDateString()})
                          </option>
                        ))}
                      </select>
                    </motion.div>
                  )}
                </div>
                
                <div className="flex gap-3 justify-end pt-4 border-t border-white/5">
                  <button onClick={handleCloseModal} className="px-4 py-2 text-[#8696a0] hover:text-white font-medium text-xs uppercase tracking-widest">Cancelar</button>
                  <button 
                    onClick={handleGeneratePreview} 
                    disabled={updating || (reportType === 'ticket' && !selectedTicketId)} 
                    className="px-6 py-2 bg-emerald-500 text-slate-950 rounded-xl font-black text-xs uppercase tracking-widest hover:bg-emerald-400 disabled:opacity-50 active:scale-95 transition-all shadow-lg shadow-emerald-500/20"
                  >
                    Gerar Pré-visualização
                  </button>
                </div>
              </>
            )}

            <button onClick={handleCloseModal} className="absolute top-4 right-4 text-[#8696a0] hover:text-white z-10">
              <X size={20} />
            </button>
            
            {activeModal === 'transfer' && (
              <>
                <h3 className="text-lg font-semibold text-white mb-4">Transferir Atendimento</h3>
                <div className="space-y-4 mb-6">
                  <div>
                    <label className="block text-[10px] font-black text-[#8696a0] uppercase tracking-widest mb-2">Para um Setor (Fila)</label>
                    <select 
                      value={selectedDepartment} 
                      onChange={(e) => {
                        setSelectedDepartment(e.target.value);
                        if(e.target.value) setSelectedUser(''); // Limpa o usuário se escolher setor
                      }}
                      className="w-full bg-[#2a3942] border border-white/10 rounded-lg p-3 text-white outline-none focus:border-[#00a884] transition-all"
                    >
                      <option value="">-- Selecione o setor de destino --</option>
                      {departments.map(d => (
                        <option key={d.id} value={d.id}>{d.name}</option>
                      ))}
                    </select>
                  </div>

                  <div className="flex items-center gap-3 py-2">
                    <div className="h-px bg-white/5 flex-1" />
                    <span className="text-[10px] font-black text-slate-600">OU</span>
                    <div className="h-px bg-white/5 flex-1" />
                  </div>

                  <div>
                    <label className="block text-[10px] font-black text-[#8696a0] uppercase tracking-widest mb-2">Direto para um Atendente</label>
                    <select 
                      value={selectedUser} 
                      onChange={(e) => {
                        setSelectedUser(e.target.value);
                        if(e.target.value) setSelectedDepartment(''); // Limpa o setor se escolher usuário
                      }}
                      className="w-full bg-[#2a3942] border border-white/10 rounded-lg p-3 text-white outline-none focus:border-[#00a884] transition-all"
                    >
                      <option value="">-- Selecione o atendente --</option>
                      {users.map(u => (
                        <option key={u.id} value={u.id}>{u.name} ({u.role})</option>
                      ))}
                    </select>
                  </div>
                </div>
                <div className="flex gap-3 justify-end">
                  <button onClick={handleCloseModal} className="px-4 py-2 text-[#8696a0] hover:text-white font-medium">Cancelar</button>
                  <button 
                    onClick={handleTransfer} 
                    disabled={updating || (!selectedUser && !selectedDepartment)} 
                    className="px-6 py-2 bg-[#00a884] text-white rounded-lg font-bold hover:bg-[#06cf9c] disabled:opacity-50 active:scale-95 transition-all shadow-lg shadow-emerald-500/10"
                  >
                    {selectedUser ? 'Transferir para Atendente' : 'Transferir para Setor'}
                  </button>
                </div>
              </>
            )}

            {activeModal === 'edit' && (
              <>
                <h3 className="text-lg font-semibold text-white mb-4">Perfil do Contato</h3>
                <div className="space-y-4 mb-6">
                  <div>
                    <label className="block text-[10px] font-black text-[#8696a0] uppercase tracking-widest mb-2">Nome Completo</label>
                    <input 
                      type="text"
                      placeholder="Nome do cliente..."
                      value={contactName} 
                      onChange={(e) => setContactName(e.target.value)}
                      className="w-full bg-[#2a3942] border border-white/10 rounded-lg p-3 text-white outline-none focus:border-[#00a884] transition-all"
                    />
                  </div>
                  
                  <div>
                    <label className="block text-[10px] font-black text-[#8696a0] uppercase tracking-widest mb-2">E-mail</label>
                    <input 
                      type="email"
                      placeholder="exemplo@email.com"
                      value={contactEmail} 
                      onChange={(e) => setContactEmail(e.target.value)}
                      className="w-full bg-[#2a3942] border border-white/10 rounded-lg p-3 text-white outline-none focus:border-[#00a884] transition-all"
                    />
                  </div>

                  <div>
                    <label className="block text-[10px] font-black text-[#8696a0] uppercase tracking-widest mb-2">Notas Rápidas</label>
                    <textarea 
                      value={contactNotes} 
                      onChange={(e) => setContactNotes(e.target.value)}
                      rows={2}
                      placeholder="Anote lembretes rápidos aqui..."
                      className="w-full bg-[#2a3942] border border-white/10 rounded-lg p-3 text-white outline-none focus:border-[#00a884] resize-none transition-all"
                    />
                  </div>

                  <div>
                    <label className="block text-[10px] font-black text-[#8696a0] uppercase tracking-widest mb-2">Observações Detalhadas</label>
                    <textarea 
                      value={contactObservations} 
                      onChange={(e) => setContactObservations(e.target.value)}
                      rows={4}
                      placeholder="Informações detalhadas sobre o cliente..."
                      className="w-full bg-[#2a3942] border border-white/10 rounded-lg p-3 text-white outline-none focus:border-[#00a884] resize-none transition-all"
                    />
                  </div>
                </div>

                <div className="flex items-center justify-between pt-4 border-t border-white/5">
                  <button 
                    onClick={handleDeleteContact} 
                    disabled={updating} 
                    className="text-red-500 hover:text-red-400 text-[10px] font-black uppercase tracking-widest flex items-center gap-2 transition-all hover:opacity-80"
                  >
                    <XCircle size={14} /> Excluir Contato
                  </button>
                  <div className="flex gap-3">
                    <button onClick={handleCloseModal} className="px-4 py-2 text-[#8696a0] hover:text-white text-xs font-bold uppercase tracking-widest">Cancelar</button>
                    <button 
                      onClick={() => handleUpdateContact({ name: contactName, email: contactEmail, notes: contactNotes, observations: contactObservations })} 
                      disabled={updating} 
                      className="px-6 py-2 bg-[#00a884] text-white rounded-xl font-black text-xs uppercase tracking-widest hover:bg-[#06cf9c] disabled:opacity-50 shadow-lg shadow-emerald-500/20 active:scale-95 transition-all"
                    >
                      Salvar Alterações
                    </button>
                  </div>
                </div>
              </>
            )}

            {activeModal === 'pdf-preview' && pdfPreviewUrl && (
              <div className="w-full h-full flex flex-col p-6 md:p-8 overflow-hidden">
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6 shrink-0">
                  <div className="space-y-1">
                    <h3 className="text-xl md:text-2xl font-black text-white uppercase tracking-tighter flex items-center gap-3">
                      <div className="w-10 h-10 rounded-xl bg-emerald-500/20 flex items-center justify-center animate-premium-pulse">
                        <Eye className="text-emerald-500" size={20} />
                      </div>
                      Relatório de Conversa
                    </h3>
                    <p className="text-[10px] text-emerald-500/60 font-black uppercase tracking-widest ml-13">Visualização Premium Ativada</p>
                  </div>
                  
                  <div className="flex items-center gap-3">
                    <button 
                      onClick={handleCloseModal} 
                      className="px-5 py-2.5 text-[#8696a0] hover:text-white font-bold uppercase text-[10px] tracking-widest transition-colors"
                    >
                      Descartar
                    </button>
                    <button 
                      onClick={handleExportPDF} 
                      className="px-8 py-3 bg-emerald-500 text-slate-950 rounded-2xl font-black uppercase text-[11px] tracking-widest hover:bg-emerald-400 transition-all flex items-center gap-3 shadow-xl shadow-emerald-500/30 active:scale-95 group"
                    >
                      <Download size={16} className="group-hover:translate-y-0.5 transition-transform" /> 
                      Baixar PDF Oficial
                    </button>
                  </div>
                </div>
                
                <div className="flex-1 overflow-y-auto bg-black/40 rounded-3xl p-4 md:p-8 border border-white/5 custom-scrollbar premium-shadow group">
                  <div className="relative group-hover:scale-[1.01] transition-transform duration-700 ease-out origin-top">
                    <img src={pdfPreviewUrl} alt="Preview do PDF" className="w-full h-auto rounded-xl shadow-2xl mx-auto ring-1 ring-white/10" />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent pointer-events-none rounded-xl" />
                  </div>
                </div>
                
                <div className="mt-6 flex items-center justify-center gap-4 shrink-0">
                  <div className="h-px flex-1 bg-gradient-to-r from-transparent via-white/5 to-transparent" />
                  <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest italic opacity-50">
                    Sistema Chatinho v2.3.7 • Exportação Dinâmica de Alta Definição
                  </p>
                  <div className="h-px flex-1 bg-gradient-to-r from-transparent via-white/5 to-transparent" />
                </div>
              </div>
            )}
          </div>
        </div>,
        document.body
      )}
    </div>
  );
}

// Componente de Áudio Customizado Premium Otimizado
const CustomAudioPlayer = React.memo(function CustomAudioPlayer({ url, isFromMe }: { url: string, isFromMe: boolean }) {
  const audioRef = useRef<HTMLAudioElement>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [progress, setProgress] = useState(0);
  const [currentTime, setCurrentTime] = useState('0:00');
  const [error, setError] = useState(false);

  const togglePlay = useCallback(() => {
    if (!audioRef.current || !url) return;
    if (isPlaying) {
      audioRef.current.pause();
    } else {
      audioRef.current.play().catch(err => {
        console.error("Erro ao reproduzir áudio:", err);
        setError(true);
      });
    }
    setIsPlaying(!isPlaying);
  }, [isPlaying, url]);

  const handleTimeUpdate = useCallback(() => {
    if (!audioRef.current) return;
    const current = audioRef.current.currentTime;
    const duration = audioRef.current.duration;
    if (duration) {
      setProgress((current / duration) * 100);
      const mins = Math.floor(current / 60);
      const secs = Math.floor(current % 60);
      setCurrentTime(`${mins}:${secs.toString().padStart(2, '0')}`);
    }
  }, []);

  const handleEnded = useCallback(() => {
    setIsPlaying(false);
    setProgress(0);
    setCurrentTime('0:00');
  }, []);

  const bars = useMemo(() => [0.3, 0.6, 0.4, 0.8, 0.5, 0.7, 0.3, 0.6, 0.4, 0.2, 0.5, 0.7, 0.3, 0.8, 0.4, 0.6, 0.3, 0.5, 0.7, 0.4], []);

  return (
    <div className={cn(
      "flex items-center gap-5 p-5 rounded-[24px] border transition-all duration-500 w-full min-w-[300px] group/audio relative overflow-hidden",
      isFromMe 
        ? "bg-slate-900/40 border-white/5 hover:bg-slate-900/60" 
        : "glass-panel border-white/5 hover:bg-white/10"
    )}>
      {/* Background Decor */}
      <div className={cn(
        "absolute -right-4 -top-4 w-24 h-24 blur-3xl opacity-10 transition-opacity group-hover/audio:opacity-20",
        isFromMe ? "bg-emerald-500" : "bg-emerald-400"
      )} />

      <button 
        onClick={togglePlay}
        className={cn(
          "w-14 h-14 rounded-2xl flex items-center justify-center transition-all active:scale-90 shrink-0 shadow-lg relative z-10",
          isFromMe ? "bg-emerald-500 text-slate-950" : "bg-emerald-500 text-slate-950"
        )}
      >
        {isPlaying ? <Pause size={28} fill="currentColor" /> : <Play size={28} className="ml-1" fill="currentColor" />}
      </button>

      <div className="flex-1 space-y-3 relative z-10">
        <div className="flex justify-between items-center px-1">
          <div className="flex gap-1.5 items-end h-7">
             {error ? (
               <span className="text-[10px] text-red-400 font-bold uppercase tracking-widest">Erro no arquivo</span>
             ) : (
               bars.map((h, i) => (
                 <motion.div 
                   key={i} 
                   initial={false}
                   animate={isPlaying ? { 
                     height: [`${h*100}%`, `${(1.2-h)*100}%`, `${h*100}%`],
                     opacity: [0.4, 1, 0.4]
                   } : { 
                     height: `${h*100}%`, 
                     opacity: 0.3 
                   }}
                   transition={isPlaying ? { 
                     repeat: Infinity, 
                     duration: 0.8, 
                     delay: i * 0.05 
                   } : { 
                     duration: 0.3 
                   }}
                   className={cn("w-1.5 rounded-full", isFromMe ? "bg-emerald-500" : "bg-emerald-400")}
                 />
               ))
             )}
          </div>
          <span className={cn("text-[10px] font-black uppercase tracking-widest font-mono opacity-60", isFromMe ? "text-emerald-500" : "text-emerald-400")}>
            {error ? '--:--' : currentTime}
          </span>
        </div>

        <div className="h-2 w-full bg-black/30 rounded-full overflow-hidden cursor-pointer relative">
          <motion.div 
            className={cn("h-full absolute left-0 top-0 glow-emerald", isFromMe ? "bg-emerald-500" : "bg-emerald-500")}
            initial={false}
            animate={{ width: `${progress}%` }}
            transition={{ type: "spring", stiffness: 300, damping: 30 }}
          />
        </div>
      </div>

      {url && (
        <audio 
          ref={audioRef} 
          src={url} 
          onTimeUpdate={handleTimeUpdate} 
          onEnded={handleEnded}
          onError={() => setError(true)}
          preload="metadata"
        />
      )}
    </div>
  );
});

// Componente de Item de Mensagem Memoizado
const MessageItem = React.memo(function MessageItem({ msg, idx, conversation, totalMessages, onPlayAudio, shouldAnimate }: any) {
  if (msg.type === 'system') {
    return (
      <motion.div
        initial={shouldAnimate ? { opacity: 0, scale: 0.95 } : false}
        animate={{ opacity: 1, scale: 1 }}
        className="flex justify-center w-full my-6 px-10"
      >
        <div className="flex flex-col items-center gap-2 max-w-lg text-center">
          <div className="px-5 py-2.5 bg-slate-900/60 backdrop-blur-xl border border-white/10 rounded-[2rem] shadow-2xl flex items-center gap-4 group hover:border-blue-500/30 transition-all">
             <div className="p-2 bg-blue-500/20 rounded-2xl text-blue-400 group-hover:scale-110 transition-transform">
               <GitBranch size={16} />
             </div>
             <p className="text-[11px] font-medium text-slate-100 leading-relaxed tracking-wide">
               {msg.body.split(/(\*\*.*?\*\*)/).map((part: string, i: number) => {
                  if (part.startsWith('**') && part.endsWith('**')) {
                    return <span key={i} className="font-black text-white decoration-blue-500/50 underline-offset-4">{part.slice(2, -2)}</span>;
                  }
                  return part;
                })}
             </p>
          </div>
          <span className="text-[9px] font-black uppercase tracking-[0.3em] text-slate-500 opacity-50">
             Log de Sistema • {new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </span>
        </div>
      </motion.div>
    );
  }

  return (
    <motion.div
      initial={shouldAnimate ? { opacity: 0, y: 10, scale: 0.95 } : false}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      className={cn(
        "flex w-full group mb-2",
        msg.fromMe ? "justify-end" : "justify-start"
      )}
    >
      <div className={cn(
        "relative max-w-[70%] transition-all duration-300",
        msg.fromMe ? "items-end" : "items-start"
      )}>
          <div
            className={cn(
              "px-4 py-3 rounded-2xl text-[14.5px] leading-relaxed shadow-xl relative overflow-hidden",
              msg.fromMe 
                ? (msg.type === 'internal' 
                    ? "bg-amber-500/10 text-amber-100 border border-amber-500/20 font-medium italic rounded-tr-sm"
                    : (msg.type === 'bot'
                        ? "bg-gradient-to-br from-indigo-600 to-blue-700 text-white font-bold rounded-tr-sm ring-1 ring-white/10"
                        : "bg-gradient-to-br from-[#10b981] to-[#059669] text-slate-950 font-bold rounded-tr-sm ring-1 ring-white/10"))
                : "bg-white/[0.03] backdrop-blur-md text-[#e9edef] border border-white/5 rounded-tl-sm shadow-md"
            )}
          >
            {msg.type === 'internal' && (
              <div className="flex items-center gap-1 mb-1.5 text-[10px] font-black text-amber-500 uppercase tracking-widest">
                <FileText size={12} /> Nota Interna
              </div>
            )}
            {/* Media Display */}
            {msg.type === 'image' && msg.mediaUrl && (
              <div className="mb-2 -mx-4 -mt-3 relative group">
                <img 
                  src={msg.mediaUrl.startsWith('http') || msg.mediaUrl.startsWith('/') ? msg.mediaUrl : `/uploads/${msg.mediaUrl}`} 
                  alt="Mídia" 
                  className="max-w-full h-auto cursor-pointer hover:opacity-90 transition-opacity"
                  onClick={() => window.open(msg.mediaUrl.startsWith('http') || msg.mediaUrl.startsWith('/') ? msg.mediaUrl : `/uploads/${msg.mediaUrl}`, '_blank')}
                />
              </div>
            )}

            {msg.type === 'audio' && msg.mediaUrl && (
              <div className="py-2 flex flex-col gap-2 min-w-[280px]">
                <CustomAudioPlayer 
                  url={msg.mediaUrl.startsWith('http') || msg.mediaUrl.startsWith('/') ? msg.mediaUrl : `/uploads/${msg.mediaUrl}`} 
                  isFromMe={msg.fromMe}
                />
              </div>
            )}

            {msg.body && (
              <p className={cn(
                "whitespace-pre-wrap break-words",
                msg.fromMe ? "selection:bg-slate-950 selection:text-emerald-400" : "selection:bg-emerald-500 selection:text-slate-950"
              )}>
                {msg.body.split(/(\*.*?\*)/).map((part: string, i: number) => {
                  if (part.startsWith('*') && part.endsWith('*')) {
                    return <strong key={i} className="font-extrabold text-inherit underline-offset-4 decoration-current/30">{part.slice(1, -1)}</strong>;
                  }
                  return part;
                })}
              </p>
            )}
          
          <div className={cn(
            "flex items-center gap-1.5 mt-2 opacity-60",
            msg.fromMe ? "justify-end" : "justify-start"
          )}>
            {msg.fromMe && msg.type === 'bot' && (
              <span className="text-[9px] font-black text-indigo-200 uppercase tracking-widest mr-auto flex items-center gap-1">
                <Bot size={10} /> Robô / Fluxo
              </span>
            )}
            <span className="text-[10px] font-bold tracking-tighter uppercase">
              {new Date(msg.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
            </span>
            {msg.fromMe && (
              <div className="flex">
                <CheckCheck size={11} className={cn(
                  msg.type === 'internal' ? "text-amber-500/80" : (msg.type === 'bot' ? "text-indigo-200/80" : "text-slate-950/80")
                )} />
              </div>
            )}
          </div>
        </div>
      </div>
    </motion.div>
  );
});
